name: Auto commit

on:
  push:
    branches:
      - master

  schedule:
    - cron: "0 7,9,17,19,23 * * 1-6"

jobs:
  auto_commit:
    runs-on: ubuntu-latest

    steps:
      - name: DEBUG
        run: echo "::debug::Ref = ${{github.ref}}"
      
      - uses: actions/checkout@v4  # Perbarui versi jika ada
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Modify last update
        run: |
          d=`date '+%Y-%m-%dT%H:%M:%SZ'`
          echo $d > LAST_UPDATED

      - name: Commit changes
        run: |
          git config --local user.email "dikkyrahmads@gmail.com"
          git config --local user.name "DikkyRahmadS"
          git add -A

          arr[0]="😂 auto commit"
          arr[1]="😱 auto commit"
          arr[2]="👿 auto commit"
          arr[3]="💩 auto commit"
          arr[4]="🙏 auto commit"
          arr[5]="🙈 auto commit"
          arr[6]="🐐 auto commit"
          arr[7]="🤖 auto commit"
          arr[8]="🟩 auto commit"
          arr[9]="👻 auto commit"

          rand=$[$RANDOM % ${#arr[@]}]

          git commit -m "${arr[$rand]}"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}
